//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.23 at 09:17:16 AM CET 
//


package cz.muni.ics.digilib.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ffIssueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ffIssueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Appendix"/>
 *     &lt;enumeration value="PeriodicalIssue"/>
 *     &lt;enumeration value="PeriodicalSupplement"/>
 *     &lt;enumeration value="PeriodicalOtherItem"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ffIssueType")
@XmlEnum
public enum FfIssueType {

    @XmlEnumValue("Appendix")
    APPENDIX("Appendix"),
    @XmlEnumValue("PeriodicalIssue")
    PERIODICAL_ISSUE("PeriodicalIssue"),
    @XmlEnumValue("PeriodicalSupplement")
    PERIODICAL_SUPPLEMENT("PeriodicalSupplement"),
    @XmlEnumValue("PeriodicalOtherItem")
    PERIODICAL_OTHER_ITEM("PeriodicalOtherItem");
    private final String value;

    FfIssueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FfIssueType fromValue(String v) {
        for (FfIssueType c: FfIssueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
