//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.23 at 09:17:16 AM CET 
//


package cz.muni.ics.digilib.domain;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.dmlcz.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PageSizeWidth_QNAME = new QName("", "PageSizeWidth");
    private final static QName _PDFPageRange_QNAME = new QName("", "PDFPageRange");
    private final static QName _LinkToReal_QNAME = new QName("", "LinkToReal");
    private final static QName _RightsURI_QNAME = new QName("", "RightsURI");
    private final static QName _Copyright_QNAME = new QName("", "Copyright");
    private final static QName _Pagination_QNAME = new QName("", "Pagination");
    private final static QName _PlaceOfPublication_QNAME = new QName("", "PlaceOfPublication");
    private final static QName _IssueNameVariant_QNAME = new QName("", "IssueNameVariant");
    private final static QName _IssueName_QNAME = new QName("", "IssueName");
    private final static QName _DOI_QNAME = new QName("", "DOI");
    private final static QName _VolumeName_QNAME = new QName("", "VolumeName");
    private final static QName _Years_QNAME = new QName("", "Years");
    private final static QName _IssueTitle_QNAME = new QName("", "IssueTitle");
    private final static QName _LinkToVirtualDescNum_QNAME = new QName("", "LinkToVirtualDescNum");
    private final static QName _ReviewedWork_QNAME = new QName("", "ReviewedWork");
    private final static QName _ISSN_QNAME = new QName("", "ISSN");
    private final static QName _Periodicity_QNAME = new QName("", "Periodicity");
    private final static QName _HomeURL_QNAME = new QName("", "HomeURL");
    private final static QName _PlaceOfPrinting_QNAME = new QName("", "PlaceOfPrinting");
    private final static QName _TitleMain_QNAME = new QName("", "TitleMain");
    private final static QName _Link_QNAME = new QName("", "Link");
    private final static QName _RealIssue_QNAME = new QName("", "RealIssue");
    private final static QName _Warning_QNAME = new QName("", "Warning");
    private final static QName _Category_QNAME = new QName("", "Category");
    private final static QName _LinkToVirtual_QNAME = new QName("", "LinkToVirtual");
    private final static QName _TitleVariant_QNAME = new QName("", "TitleVariant");
    private final static QName _EmbargoEndDate_QNAME = new QName("", "EmbargoEndDate");
    private final static QName _RightsLicense_QNAME = new QName("", "RightsLicense");
    private final static QName _PublicationEnd_QNAME = new QName("", "PublicationEnd");
    private final static QName _NextSeries_QNAME = new QName("", "NextSeries");
    private final static QName _LinkToVirtualDesc_QNAME = new QName("", "LinkToVirtualDesc");
    private final static QName _ISBN_QNAME = new QName("", "ISBN");
    private final static QName _Language_QNAME = new QName("", "Language");
    private final static QName _PageSizeHeight_QNAME = new QName("", "PageSizeHeight");
    private final static QName _ExternalContent_QNAME = new QName("", "ExternalContent");
    private final static QName _MovingWall_QNAME = new QName("", "MovingWall");
    private final static QName _PreviousSeries_QNAME = new QName("", "PreviousSeries");
    private final static QName _PublYear_QNAME = new QName("", "PublYear");
    private final static QName _PublicationDate_QNAME = new QName("", "PublicationDate");
    private final static QName _ProjectNumber_QNAME = new QName("", "ProjectNumber");
    private final static QName _TitleLang_QNAME = new QName("", "TitleLang");
    private final static QName _LinkToVirtualData_QNAME = new QName("", "LinkToVirtualData");
    private final static QName _SerialTitle_QNAME = new QName("", "SerialTitle");
    private final static QName _Publisher_QNAME = new QName("", "Publisher");
    private final static QName _PublicationStart_QNAME = new QName("", "PublicationStart");
    private final static QName _LinkToRealDesc_QNAME = new QName("", "LinkToRealDesc");
    private final static QName _PartAuthor_QNAME = new QName("", "PartAuthor");
    private final static QName _PDFOrigin_QNAME = new QName("", "PDFOrigin");
    private final static QName _Summary_QNAME = new QName("", "Summary");
    private final static QName _PartTitle_QNAME = new QName("", "PartTitle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.dmlcz.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Issue }
     * 
     */
    public Issue createIssue() {
        return new Issue();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link PageSize }
     * 
     */
    public PageSize createPageSize() {
        return new PageSize();
    }

    /**
     * Create an instance of {@link TitleVariantMain }
     * 
     */
    public TitleVariantMain createTitleVariantMain() {
        return new TitleVariantMain();
    }

    /**
     * Create an instance of {@link Volume }
     * 
     */
    public Volume createVolume() {
        return new Volume();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public Contributor createContributor() {
        return new Contributor();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link Periodical }
     * 
     */
    public Periodical createPeriodical() {
        return new Periodical();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link I18NText }
     * 
     */
    public I18NText createI18NText() {
        return new I18NText();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PageSizeWidth")
    public JAXBElement<String> createPageSizeWidth(String value) {
        return new JAXBElement<String>(_PageSizeWidth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PDFPageRange")
    public JAXBElement<String> createPDFPageRange(String value) {
        return new JAXBElement<String>(_PDFPageRange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToReal")
    public JAXBElement<String> createLinkToReal(String value) {
        return new JAXBElement<String>(_LinkToReal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RightsURI")
    public JAXBElement<String> createRightsURI(String value) {
        return new JAXBElement<String>(_RightsURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Copyright")
    public JAXBElement<String> createCopyright(String value) {
        return new JAXBElement<String>(_Copyright_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pagination")
    public JAXBElement<String> createPagination(String value) {
        return new JAXBElement<String>(_Pagination_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PlaceOfPublication")
    public JAXBElement<String> createPlaceOfPublication(String value) {
        return new JAXBElement<String>(_PlaceOfPublication_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IssueNameVariant")
    public JAXBElement<String> createIssueNameVariant(String value) {
        return new JAXBElement<String>(_IssueNameVariant_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IssueName")
    public JAXBElement<String> createIssueName(String value) {
        return new JAXBElement<String>(_IssueName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOI")
    public JAXBElement<String> createDOI(String value) {
        return new JAXBElement<String>(_DOI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VolumeName")
    public JAXBElement<String> createVolumeName(String value) {
        return new JAXBElement<String>(_VolumeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Years")
    public JAXBElement<String> createYears(String value) {
        return new JAXBElement<String>(_Years_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IssueTitle")
    public JAXBElement<String> createIssueTitle(String value) {
        return new JAXBElement<String>(_IssueTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToVirtualDescNum")
    public JAXBElement<String> createLinkToVirtualDescNum(String value) {
        return new JAXBElement<String>(_LinkToVirtualDescNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReviewedWork")
    public JAXBElement<String> createReviewedWork(String value) {
        return new JAXBElement<String>(_ReviewedWork_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ISSN")
    public JAXBElement<String> createISSN(String value) {
        return new JAXBElement<String>(_ISSN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Periodicity")
    public JAXBElement<String> createPeriodicity(String value) {
        return new JAXBElement<String>(_Periodicity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeURL")
    public JAXBElement<String> createHomeURL(String value) {
        return new JAXBElement<String>(_HomeURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PlaceOfPrinting")
    public JAXBElement<String> createPlaceOfPrinting(String value) {
        return new JAXBElement<String>(_PlaceOfPrinting_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitleMain")
    public JAXBElement<String> createTitleMain(String value) {
        return new JAXBElement<String>(_TitleMain_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Link")
    public JAXBElement<String> createLink(String value) {
        return new JAXBElement<String>(_Link_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RealIssue")
    public JAXBElement<String> createRealIssue(String value) {
        return new JAXBElement<String>(_RealIssue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Warning")
    public JAXBElement<String> createWarning(String value) {
        return new JAXBElement<String>(_Warning_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfSerialCatetory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Category")
    public JAXBElement<FfSerialCatetory> createCategory(FfSerialCatetory value) {
        return new JAXBElement<FfSerialCatetory>(_Category_QNAME, FfSerialCatetory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToVirtual")
    public JAXBElement<String> createLinkToVirtual(String value) {
        return new JAXBElement<String>(_LinkToVirtual_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitleVariant")
    public JAXBElement<String> createTitleVariant(String value) {
        return new JAXBElement<String>(_TitleVariant_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmbargoEndDate")
    public JAXBElement<String> createEmbargoEndDate(String value) {
        return new JAXBElement<String>(_EmbargoEndDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfRightsLicense }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RightsLicense")
    public JAXBElement<FfRightsLicense> createRightsLicense(FfRightsLicense value) {
        return new JAXBElement<FfRightsLicense>(_RightsLicense_QNAME, FfRightsLicense.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublicationEnd")
    public JAXBElement<BigInteger> createPublicationEnd(BigInteger value) {
        return new JAXBElement<BigInteger>(_PublicationEnd_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NextSeries")
    public JAXBElement<String> createNextSeries(String value) {
        return new JAXBElement<String>(_NextSeries_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToVirtualDesc")
    public JAXBElement<String> createLinkToVirtualDesc(String value) {
        return new JAXBElement<String>(_LinkToVirtualDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ISBN")
    public JAXBElement<String> createISBN(String value) {
        return new JAXBElement<String>(_ISBN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PageSizeHeight")
    public JAXBElement<String> createPageSizeHeight(String value) {
        return new JAXBElement<String>(_PageSizeHeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExternalContent")
    public JAXBElement<String> createExternalContent(String value) {
        return new JAXBElement<String>(_ExternalContent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MovingWall")
    public JAXBElement<String> createMovingWall(String value) {
        return new JAXBElement<String>(_MovingWall_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PreviousSeries")
    public JAXBElement<String> createPreviousSeries(String value) {
        return new JAXBElement<String>(_PreviousSeries_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublYear")
    public JAXBElement<String> createPublYear(String value) {
        return new JAXBElement<String>(_PublYear_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublicationDate")
    public JAXBElement<String> createPublicationDate(String value) {
        return new JAXBElement<String>(_PublicationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProjectNumber")
    public JAXBElement<String> createProjectNumber(String value) {
        return new JAXBElement<String>(_ProjectNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TitleLang")
    public JAXBElement<String> createTitleLang(String value) {
        return new JAXBElement<String>(_TitleLang_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToVirtualData")
    public JAXBElement<String> createLinkToVirtualData(String value) {
        return new JAXBElement<String>(_LinkToVirtualData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SerialTitle")
    public JAXBElement<String> createSerialTitle(String value) {
        return new JAXBElement<String>(_SerialTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Publisher")
    public JAXBElement<String> createPublisher(String value) {
        return new JAXBElement<String>(_Publisher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublicationStart")
    public JAXBElement<BigInteger> createPublicationStart(BigInteger value) {
        return new JAXBElement<BigInteger>(_PublicationStart_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToRealDesc")
    public JAXBElement<String> createLinkToRealDesc(String value) {
        return new JAXBElement<String>(_LinkToRealDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartAuthor")
    public JAXBElement<String> createPartAuthor(String value) {
        return new JAXBElement<String>(_PartAuthor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfPDFOrigin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PDFOrigin")
    public JAXBElement<FfPDFOrigin> createPDFOrigin(FfPDFOrigin value) {
        return new JAXBElement<FfPDFOrigin>(_PDFOrigin_QNAME, FfPDFOrigin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartTitle")
    public JAXBElement<String> createPartTitle(String value) {
        return new JAXBElement<String>(_PartTitle_QNAME, String.class, null, value);
    }

}
