//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 10:15:26 AM CEST 
//


package cz.muni.ics.dmlcz5.domain;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="status" type="{}dmlczStatus" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{}dmlczI18nText" maxOccurs="unbounded"/>
 *         &lt;element name="author" type="{}dmlczPerson" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="language" type="{}dmlczLang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="date" type="{}dmlczYear" minOccurs="0"/>
 *         &lt;element name="publ_info" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="keyword" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="summary" type="{}dmlczI18nText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lang_summary" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="msc" type="{}dmlczMSC" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="idMR" type="{}dmlczMR" minOccurs="0"/>
 *         &lt;element name="idZBL" type="{}dmlczZBL" minOccurs="0"/>
 *         &lt;element name="idJFM" type="{}dmlczJFM" minOccurs="0"/>
 *         &lt;element name="doi" type="{}dmlczDOI" minOccurs="0"/>
 *         &lt;element name="idUlrych" type="{}dmlczUlrych" minOccurs="0"/>
 *         &lt;element name="category" type="{}dmlczCategory"/>
 *         &lt;element name="work_type" type="{}dmlczWorkType" minOccurs="0"/>
 *         &lt;element name="ext_link" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ext_url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ext_note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="range_pages" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="access" type="{}dmlczBoolean" minOccurs="0"/>
 *         &lt;element name="note" type="{}dmlczNote" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="link" type="{}dmlczLink" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="link_oneway" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="section" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "status",
    "code",
    "title",
    "author",
    "language",
    "date",
    "publInfo",
    "source",
    "copyright",
    "keyword",
    "summary",
    "langSummary",
    "msc",
    "idMR",
    "idZBL",
    "idJFM",
    "doi",
    "idUlrych",
    "category",
    "workType",
    "extLink",
    "extUrl",
    "extNote",
    "range",
    "rangePages",
    "access",
    "note",
    "link",
    "linkOneway",
    "section"
})
@XmlRootElement(name = "article")
public class Article {

    protected BigInteger number;
    protected DmlczStatus status;
    protected String code;
    @XmlElement(required = true)
    protected List<DmlczI18NText> title;
    protected List<DmlczPerson> author;
    protected List<String> language;
    protected Integer date;
    @XmlElement(name = "publ_info")
    protected String publInfo;
    protected String source;
    protected String copyright;
    protected List<String> keyword;
    protected List<DmlczI18NText> summary;
    @XmlElement(name = "lang_summary")
    protected List<String> langSummary;
    protected List<String> msc;
    protected String idMR;
    protected String idZBL;
    protected String idJFM;
    protected String doi;
    protected BigInteger idUlrych;
    @XmlElement(required = true)
    protected DmlczCategory category;
    @XmlElement(name = "work_type")
    protected DmlczWorkType workType;
    @XmlElement(name = "ext_link")
    protected String extLink;
    @XmlElement(name = "ext_url")
    protected String extUrl;
    @XmlElement(name = "ext_note")
    protected String extNote;
    protected String range;
    @XmlElement(name = "range_pages")
    protected String rangePages;
    protected DmlczBoolean access;
    protected List<DmlczNote> note;
    protected List<DmlczLink> link;
    @XmlElement(name = "link_oneway")
    protected List<String> linkOneway;
    protected String section;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczStatus }
     *     
     */
    public DmlczStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczStatus }
     *     
     */
    public void setStatus(DmlczStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczI18NText }
     * 
     * 
     */
    public List<DmlczI18NText> getTitle() {
        if (title == null) {
            title = new ArrayList<DmlczI18NText>();
        }
        return this.title;
    }

    /**
     * Gets the value of the author property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the author property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczPerson }
     * 
     * 
     */
    public List<DmlczPerson> getAuthor() {
        if (author == null) {
            author = new ArrayList<DmlczPerson>();
        }
        return this.author;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguage() {
        if (language == null) {
            language = new ArrayList<String>();
        }
        return this.language;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDate(Integer value) {
        this.date = value;
    }

    /**
     * Gets the value of the publInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublInfo() {
        return publInfo;
    }

    /**
     * Sets the value of the publInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublInfo(String value) {
        this.publInfo = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKeyword() {
        if (keyword == null) {
            keyword = new ArrayList<String>();
        }
        return this.keyword;
    }

    /**
     * Gets the value of the summary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the summary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczI18NText }
     * 
     * 
     */
    public List<DmlczI18NText> getSummary() {
        if (summary == null) {
            summary = new ArrayList<DmlczI18NText>();
        }
        return this.summary;
    }

    /**
     * Gets the value of the langSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the langSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLangSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLangSummary() {
        if (langSummary == null) {
            langSummary = new ArrayList<String>();
        }
        return this.langSummary;
    }

    /**
     * Gets the value of the msc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMsc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMsc() {
        if (msc == null) {
            msc = new ArrayList<String>();
        }
        return this.msc;
    }

    /**
     * Gets the value of the idMR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdMR() {
        return idMR;
    }

    /**
     * Sets the value of the idMR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdMR(String value) {
        this.idMR = value;
    }

    /**
     * Gets the value of the idZBL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdZBL() {
        return idZBL;
    }

    /**
     * Sets the value of the idZBL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdZBL(String value) {
        this.idZBL = value;
    }

    /**
     * Gets the value of the idJFM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdJFM() {
        return idJFM;
    }

    /**
     * Sets the value of the idJFM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdJFM(String value) {
        this.idJFM = value;
    }

    /**
     * Gets the value of the doi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoi() {
        return doi;
    }

    /**
     * Sets the value of the doi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoi(String value) {
        this.doi = value;
    }

    /**
     * Gets the value of the idUlrych property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdUlrych() {
        return idUlrych;
    }

    /**
     * Sets the value of the idUlrych property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdUlrych(BigInteger value) {
        this.idUlrych = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczCategory }
     *     
     */
    public DmlczCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczCategory }
     *     
     */
    public void setCategory(DmlczCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the workType property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczWorkType }
     *     
     */
    public DmlczWorkType getWorkType() {
        return workType;
    }

    /**
     * Sets the value of the workType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczWorkType }
     *     
     */
    public void setWorkType(DmlczWorkType value) {
        this.workType = value;
    }

    /**
     * Gets the value of the extLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtLink() {
        return extLink;
    }

    /**
     * Sets the value of the extLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtLink(String value) {
        this.extLink = value;
    }

    /**
     * Gets the value of the extUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtUrl() {
        return extUrl;
    }

    /**
     * Sets the value of the extUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtUrl(String value) {
        this.extUrl = value;
    }

    /**
     * Gets the value of the extNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtNote() {
        return extNote;
    }

    /**
     * Sets the value of the extNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtNote(String value) {
        this.extNote = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRange(String value) {
        this.range = value;
    }

    /**
     * Gets the value of the rangePages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangePages() {
        return rangePages;
    }

    /**
     * Sets the value of the rangePages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangePages(String value) {
        this.rangePages = value;
    }

    /**
     * Gets the value of the access property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczBoolean }
     *     
     */
    public DmlczBoolean getAccess() {
        return access;
    }

    /**
     * Sets the value of the access property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczBoolean }
     *     
     */
    public void setAccess(DmlczBoolean value) {
        this.access = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczNote }
     * 
     * 
     */
    public List<DmlczNote> getNote() {
        if (note == null) {
            note = new ArrayList<DmlczNote>();
        }
        return this.note;
    }

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczLink }
     * 
     * 
     */
    public List<DmlczLink> getLink() {
        if (link == null) {
            link = new ArrayList<DmlczLink>();
        }
        return this.link;
    }

    /**
     * Gets the value of the linkOneway property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkOneway property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkOneway().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLinkOneway() {
        if (linkOneway == null) {
            linkOneway = new ArrayList<String>();
        }
        return this.linkOneway;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection(String value) {
        this.section = value;
    }

}
