//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 10:16:04 AM CEST 
//


package cz.muni.ics.dmlcz5.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dmlczCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dmlczCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="math"/>
 *     &lt;enumeration value="news"/>
 *     &lt;enumeration value="history"/>
 *     &lt;enumeration value="politics"/>
 *     &lt;enumeration value="editorial"/>
 *     &lt;enumeration value="contents"/>
 *     &lt;enumeration value="other"/>
 *     &lt;enumeration value="review"/>
 *     &lt;enumeration value="physics"/>
 *     &lt;enumeration value="chemistry"/>
 *     &lt;enumeration value="astronomy"/>
 *     &lt;enumeration value="informatics"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dmlczCategory")
@XmlEnum
public enum DmlczCategory {

    @XmlEnumValue("math")
    MATH("math"),
    @XmlEnumValue("news")
    NEWS("news"),
    @XmlEnumValue("history")
    HISTORY("history"),
    @XmlEnumValue("politics")
    POLITICS("politics"),
    @XmlEnumValue("editorial")
    EDITORIAL("editorial"),
    @XmlEnumValue("contents")
    CONTENTS("contents"),
    @XmlEnumValue("other")
    OTHER("other"),
    @XmlEnumValue("review")
    REVIEW("review"),
    @XmlEnumValue("physics")
    PHYSICS("physics"),
    @XmlEnumValue("chemistry")
    CHEMISTRY("chemistry"),
    @XmlEnumValue("astronomy")
    ASTRONOMY("astronomy"),
    @XmlEnumValue("informatics")
    INFORMATICS("informatics");
    private final String value;

    DmlczCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DmlczCategory fromValue(String v) {
        for (DmlczCategory c: DmlczCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
