//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 10:16:04 AM CEST 
//


package cz.muni.ics.dmlcz5.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dmlczStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dmlczStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="in progress"/>
 *     &lt;enumeration value="completed"/>
 *     &lt;enumeration value="untouched"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dmlczStatus")
@XmlEnum
public enum DmlczStatus {

    @XmlEnumValue("in progress")
    IN_PROGRESS("in progress"),
    @XmlEnumValue("completed")
    COMPLETED("completed"),
    @XmlEnumValue("untouched")
    UNTOUCHED("untouched");
    private final String value;

    DmlczStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DmlczStatus fromValue(String v) {
        for (DmlczStatus c: DmlczStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
