//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 10:15:59 AM CEST 
//


package cz.muni.ics.dmlcz5.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="issn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *         &lt;element name="year_from" type="{}dmlczYear"/>
 *         &lt;element name="year_to" type="{}dmlczYear"/>
 *         &lt;element name="title" type="{}dmlczI18nText"/>
 *         &lt;element name="abbrev" type="{}dmlczAbbrev"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "issn",
    "yearFrom",
    "yearTo",
    "title",
    "abbrev"
})
public class HistoryTitle {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected Object issn;
    @XmlElement(name = "year_from")
    protected int yearFrom;
    @XmlElement(name = "year_to")
    protected int yearTo;
    @XmlElement(required = true)
    protected DmlczI18NText title;
    @XmlElement(required = true)
    protected String abbrev;

    /**
     * Gets the value of the issn property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIssn() {
        return issn;
    }

    /**
     * Sets the value of the issn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIssn(Object value) {
        this.issn = value;
    }

    /**
     * Gets the value of the yearFrom property.
     * 
     */
    public int getYearFrom() {
        return yearFrom;
    }

    /**
     * Sets the value of the yearFrom property.
     * 
     */
    public void setYearFrom(int value) {
        this.yearFrom = value;
    }

    /**
     * Gets the value of the yearTo property.
     * 
     */
    public int getYearTo() {
        return yearTo;
    }

    /**
     * Sets the value of the yearTo property.
     * 
     */
    public void setYearTo(int value) {
        this.yearTo = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczI18NText }
     *     
     */
    public DmlczI18NText getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczI18NText }
     *     
     */
    public void setTitle(DmlczI18NText value) {
        this.title = value;
    }

    /**
     * Gets the value of the abbrev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbbrev() {
        return abbrev;
    }

    /**
     * Sets the value of the abbrev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbbrev(String value) {
        this.abbrev = value;
    }

}
