//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 10:15:35 AM CEST 
//


package cz.muni.ics.dmlcz5.domain;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="date" type="{}dmlczYear"/>
 *         &lt;element name="status" type="{}dmlczStatus" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="number_in_series" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="acronym" type="{}dmlczAbbrev" minOccurs="0"/>
 *         &lt;element name="conference_number" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="formalized_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{}dmlczI18nText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="titlecomp" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{}dmlczI18nText"/>
 *                   &lt;element name="sub_title" type="{}dmlczI18nText" minOccurs="0"/>
 *                   &lt;element name="volume" type="{}dmlczVolumeTitle"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="lang" type="{}dmlczLang" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="editor" type="{}dmlczPerson" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="creator" type="{}dmlczPerson" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="contributor" type="{}dmlczPerson" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="place" type="{}dmlczPlace" minOccurs="0"/>
 *         &lt;element name="organized_by" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="isbn" type="{}dmlczISBN" minOccurs="0"/>
 *         &lt;element name="language" type="{}dmlczLang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="issue_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="copyright" type="{}dmlczCopyright" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="publishers" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="publ_year" type="{}dmlczYear" minOccurs="0"/>
 *         &lt;element name="places" type="{}dmlczPlace" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="series_title" type="{}dmlczI18nText" minOccurs="0"/>
 *         &lt;element name="series_short" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="series_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="issn" type="{}dmlczISSN" minOccurs="0"/>
 *         &lt;element name="issuer" type="{}dmlczPerson" minOccurs="0"/>
 *         &lt;element name="printer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{}dmlczI18nText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="msc" type="{}dmlczMSC" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="idMR" type="{}dmlczMR" minOccurs="0"/>
 *         &lt;element name="idZBL" type="{}dmlczZBL" minOccurs="0"/>
 *         &lt;element name="ExternalProceeding" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="link" type="{}dmlczLink" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="paper_size" type="{}dmlczPaperSize" minOccurs="0"/>
 *         &lt;element name="note" type="{}dmlczNote" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="structure" type="{}dmlczBoolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "number",
    "date",
    "status",
    "name",
    "numberInSeries",
    "acronym",
    "conferenceNumber",
    "formalizedName",
    "title",
    "titlecomp",
    "editor",
    "creator",
    "contributor",
    "place",
    "organizedBy",
    "isbn",
    "language",
    "issueNumber",
    "copyright",
    "publishers",
    "publYear",
    "places",
    "seriesTitle",
    "seriesShort",
    "seriesNumber",
    "issn",
    "issuer",
    "printer",
    "description",
    "msc",
    "idMR",
    "idZBL",
    "externalProceeding",
    "link",
    "paperSize",
    "note",
    "structure"
})
@XmlRootElement(name = "issue")
public class Issue {

    protected BigInteger number;
    protected int date;
    protected DmlczStatus status;
    protected String name;
    @XmlElement(name = "number_in_series")
    protected BigInteger numberInSeries;
    protected String acronym;
    @XmlElement(name = "conference_number")
    protected BigInteger conferenceNumber;
    @XmlElement(name = "formalized_name")
    protected String formalizedName;
    protected List<DmlczI18NText> title;
    protected List<Titlecomp> titlecomp;
    protected List<DmlczPerson> editor;
    protected List<DmlczPerson> creator;
    protected List<DmlczPerson> contributor;
    protected String place;
    @XmlElement(name = "organized_by")
    protected List<String> organizedBy;
    protected String isbn;
    protected List<String> language;
    @XmlElement(name = "issue_number")
    protected String issueNumber;
    protected List<String> copyright;
    protected List<String> publishers;
    @XmlElement(name = "publ_year")
    protected Integer publYear;
    protected List<String> places;
    @XmlElement(name = "series_title")
    protected DmlczI18NText seriesTitle;
    @XmlElement(name = "series_short")
    protected String seriesShort;
    @XmlElement(name = "series_number")
    protected String seriesNumber;
    protected String issn;
    protected DmlczPerson issuer;
    protected String printer;
    protected List<DmlczI18NText> description;
    protected List<String> msc;
    protected String idMR;
    protected String idZBL;
    @XmlElement(name = "ExternalProceeding")
    protected ExternalProceeding externalProceeding;
    protected List<DmlczLink> link;
    @XmlElement(name = "paper_size")
    protected DmlczPaperSize paperSize;
    protected List<DmlczNote> note;
    protected DmlczBoolean structure;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the date property.
     * 
     */
    public int getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     */
    public void setDate(int value) {
        this.date = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczStatus }
     *     
     */
    public DmlczStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczStatus }
     *     
     */
    public void setStatus(DmlczStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the numberInSeries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberInSeries() {
        return numberInSeries;
    }

    /**
     * Sets the value of the numberInSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberInSeries(BigInteger value) {
        this.numberInSeries = value;
    }

    /**
     * Gets the value of the acronym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcronym() {
        return acronym;
    }

    /**
     * Sets the value of the acronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcronym(String value) {
        this.acronym = value;
    }

    /**
     * Gets the value of the conferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConferenceNumber() {
        return conferenceNumber;
    }

    /**
     * Sets the value of the conferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConferenceNumber(BigInteger value) {
        this.conferenceNumber = value;
    }

    /**
     * Gets the value of the formalizedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormalizedName() {
        return formalizedName;
    }

    /**
     * Sets the value of the formalizedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormalizedName(String value) {
        this.formalizedName = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczI18NText }
     * 
     * 
     */
    public List<DmlczI18NText> getTitle() {
        if (title == null) {
            title = new ArrayList<DmlczI18NText>();
        }
        return this.title;
    }

    /**
     * Gets the value of the titlecomp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titlecomp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitlecomp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Titlecomp }
     * 
     * 
     */
    public List<Titlecomp> getTitlecomp() {
        if (titlecomp == null) {
            titlecomp = new ArrayList<Titlecomp>();
        }
        return this.titlecomp;
    }

    /**
     * Gets the value of the editor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the editor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEditor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczPerson }
     * 
     * 
     */
    public List<DmlczPerson> getEditor() {
        if (editor == null) {
            editor = new ArrayList<DmlczPerson>();
        }
        return this.editor;
    }

    /**
     * Gets the value of the creator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczPerson }
     * 
     * 
     */
    public List<DmlczPerson> getCreator() {
        if (creator == null) {
            creator = new ArrayList<DmlczPerson>();
        }
        return this.creator;
    }

    /**
     * Gets the value of the contributor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczPerson }
     * 
     * 
     */
    public List<DmlczPerson> getContributor() {
        if (contributor == null) {
            contributor = new ArrayList<DmlczPerson>();
        }
        return this.contributor;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlace(String value) {
        this.place = value;
    }

    /**
     * Gets the value of the organizedBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizedBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizedBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOrganizedBy() {
        if (organizedBy == null) {
            organizedBy = new ArrayList<String>();
        }
        return this.organizedBy;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsbn(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguage() {
        if (language == null) {
            language = new ArrayList<String>();
        }
        return this.language;
    }

    /**
     * Gets the value of the issueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueNumber() {
        return issueNumber;
    }

    /**
     * Sets the value of the issueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueNumber(String value) {
        this.issueNumber = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copyright property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopyright().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCopyright() {
        if (copyright == null) {
            copyright = new ArrayList<String>();
        }
        return this.copyright;
    }

    /**
     * Gets the value of the publishers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publishers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublishers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPublishers() {
        if (publishers == null) {
            publishers = new ArrayList<String>();
        }
        return this.publishers;
    }

    /**
     * Gets the value of the publYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPublYear() {
        return publYear;
    }

    /**
     * Sets the value of the publYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPublYear(Integer value) {
        this.publYear = value;
    }

    /**
     * Gets the value of the places property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the places property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlaces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlaces() {
        if (places == null) {
            places = new ArrayList<String>();
        }
        return this.places;
    }

    /**
     * Gets the value of the seriesTitle property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczI18NText }
     *     
     */
    public DmlczI18NText getSeriesTitle() {
        return seriesTitle;
    }

    /**
     * Sets the value of the seriesTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczI18NText }
     *     
     */
    public void setSeriesTitle(DmlczI18NText value) {
        this.seriesTitle = value;
    }

    /**
     * Gets the value of the seriesShort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriesShort() {
        return seriesShort;
    }

    /**
     * Sets the value of the seriesShort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriesShort(String value) {
        this.seriesShort = value;
    }

    /**
     * Gets the value of the seriesNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriesNumber() {
        return seriesNumber;
    }

    /**
     * Sets the value of the seriesNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriesNumber(String value) {
        this.seriesNumber = value;
    }

    /**
     * Gets the value of the issn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssn() {
        return issn;
    }

    /**
     * Sets the value of the issn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssn(String value) {
        this.issn = value;
    }

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczPerson }
     *     
     */
    public DmlczPerson getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczPerson }
     *     
     */
    public void setIssuer(DmlczPerson value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the printer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrinter() {
        return printer;
    }

    /**
     * Sets the value of the printer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrinter(String value) {
        this.printer = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczI18NText }
     * 
     * 
     */
    public List<DmlczI18NText> getDescription() {
        if (description == null) {
            description = new ArrayList<DmlczI18NText>();
        }
        return this.description;
    }

    /**
     * Gets the value of the msc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMsc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMsc() {
        if (msc == null) {
            msc = new ArrayList<String>();
        }
        return this.msc;
    }

    /**
     * Gets the value of the idMR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdMR() {
        return idMR;
    }

    /**
     * Sets the value of the idMR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdMR(String value) {
        this.idMR = value;
    }

    /**
     * Gets the value of the idZBL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdZBL() {
        return idZBL;
    }

    /**
     * Sets the value of the idZBL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdZBL(String value) {
        this.idZBL = value;
    }

    /**
     * Gets the value of the externalProceeding property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalProceeding }
     *     
     */
    public ExternalProceeding getExternalProceeding() {
        return externalProceeding;
    }

    /**
     * Sets the value of the externalProceeding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalProceeding }
     *     
     */
    public void setExternalProceeding(ExternalProceeding value) {
        this.externalProceeding = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczLink }
     * 
     * 
     */
    public List<DmlczLink> getLink() {
        if (link == null) {
            link = new ArrayList<DmlczLink>();
        }
        return this.link;
    }

    /**
     * Gets the value of the paperSize property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczPaperSize }
     *     
     */
    public DmlczPaperSize getPaperSize() {
        return paperSize;
    }

    /**
     * Sets the value of the paperSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczPaperSize }
     *     
     */
    public void setPaperSize(DmlczPaperSize value) {
        this.paperSize = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczNote }
     * 
     * 
     */
    public List<DmlczNote> getNote() {
        if (note == null) {
            note = new ArrayList<DmlczNote>();
        }
        return this.note;
    }

    /**
     * Gets the value of the structure property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczBoolean }
     *     
     */
    public DmlczBoolean getStructure() {
        return structure;
    }

    /**
     * Sets the value of the structure property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczBoolean }
     *     
     */
    public void setStructure(DmlczBoolean value) {
        this.structure = value;
    }

}
