//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 10:15:59 AM CEST 
//


package cz.muni.ics.dmlcz5.domain;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{}dmlczStatus"/>
 *         &lt;element name="issn" type="{}dmlczISSN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="coden" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="title" type="{}dmlczI18nText"/>
 *         &lt;element name="TitleAbbreviated" type="{}dmlczAbbrev" minOccurs="0"/>
 *         &lt;element name="description" type="{}dmlczI18nText" minOccurs="0"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="copyright" type="{}dmlczI18nText" minOccurs="0"/>
 *         &lt;element name="FormerJournal" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="yearFrom" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="yearTo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="link" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="history_title" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="issn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                   &lt;element name="year_from" type="{}dmlczYear"/>
 *                   &lt;element name="year_to" type="{}dmlczYear"/>
 *                   &lt;element name="title" type="{}dmlczI18nText"/>
 *                   &lt;element name="abbrev" type="{}dmlczAbbrev"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="publisher" type="{}dmlczI18nText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pub-house" type="{}dmlczI18nText" minOccurs="0"/>
 *         &lt;element name="place" type="{}dmlczI18nText" minOccurs="0"/>
 *         &lt;element name="country" type="{}dmlczCountry" minOccurs="0"/>
 *         &lt;element name="language" type="{}dmlczLang" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="start" type="{}dmlczYear" minOccurs="0"/>
 *         &lt;element name="end" type="{}dmlczYear" minOccurs="0"/>
 *         &lt;element name="periodicity" type="{}dmlczPeriodicity" minOccurs="0"/>
 *         &lt;element name="editor_email" type="{}dmlczEmail" minOccurs="0"/>
 *         &lt;element name="watch_email" type="{}dmlczEmail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MovingWall" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="paper_size" type="{}dmlczPaperSize"/>
 *         &lt;element name="note" type="{}dmlczNote" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="user_right" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="volume" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="date" type="{}dmlczYear"/>
 *                   &lt;element name="status" type="{}dmlczStatus" minOccurs="0"/>
 *                   &lt;element name="note" type="{}dmlczNote" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="title" type="{}dmlczI18nText" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="description" type="{}dmlczI18nText" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "issn",
    "coden",
    "title",
    "titleAbbreviated",
    "description",
    "url",
    "copyright",
    "formerJournal",
    "historyTitle",
    "publisher",
    "pubHouse",
    "place",
    "country",
    "language",
    "start",
    "end",
    "periodicity",
    "editorEmail",
    "watchEmail",
    "movingWall",
    "paperSize",
    "note",
    "userRight",
    "volume"
})
@XmlRootElement(name = "journal")
public class Journal {

    @XmlElement(required = true)
    protected DmlczStatus status;
    protected List<String> issn;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected List<String> coden;
    @XmlElement(required = true)
    protected DmlczI18NText title;
    @XmlElement(name = "TitleAbbreviated")
    protected String titleAbbreviated;
    protected DmlczI18NText description;
    @XmlSchemaType(name = "anyURI")
    protected String url;
    protected DmlczI18NText copyright;
    @XmlElement(name = "FormerJournal")
    protected List<FormerJournal> formerJournal;
    @XmlElement(name = "history_title")
    protected HistoryTitle historyTitle;
    protected List<DmlczI18NText> publisher;
    @XmlElement(name = "pub-house")
    protected DmlczI18NText pubHouse;
    protected DmlczI18NText place;
    protected String country;
    protected List<String> language;
    protected Integer start;
    protected Integer end;
    protected String periodicity;
    @XmlElement(name = "editor_email")
    protected String editorEmail;
    @XmlElement(name = "watch_email")
    protected List<String> watchEmail;
    @XmlElement(name = "MovingWall")
    protected BigInteger movingWall;
    @XmlElement(name = "paper_size", required = true)
    protected DmlczPaperSize paperSize;
    protected List<DmlczNote> note;
    @XmlElement(name = "user_right")
    protected List<UserRight> userRight;
    @XmlElement(required = true)
    protected List<Volume> volume;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczStatus }
     *     
     */
    public DmlczStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczStatus }
     *     
     */
    public void setStatus(DmlczStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the issn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIssn() {
        if (issn == null) {
            issn = new ArrayList<String>();
        }
        return this.issn;
    }

    /**
     * Gets the value of the coden property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coden property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoden().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCoden() {
        if (coden == null) {
            coden = new ArrayList<String>();
        }
        return this.coden;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczI18NText }
     *     
     */
    public DmlczI18NText getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczI18NText }
     *     
     */
    public void setTitle(DmlczI18NText value) {
        this.title = value;
    }

    /**
     * Gets the value of the titleAbbreviated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleAbbreviated() {
        return titleAbbreviated;
    }

    /**
     * Sets the value of the titleAbbreviated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleAbbreviated(String value) {
        this.titleAbbreviated = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczI18NText }
     *     
     */
    public DmlczI18NText getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczI18NText }
     *     
     */
    public void setDescription(DmlczI18NText value) {
        this.description = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczI18NText }
     *     
     */
    public DmlczI18NText getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczI18NText }
     *     
     */
    public void setCopyright(DmlczI18NText value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the formerJournal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formerJournal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormerJournal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormerJournal }
     * 
     * 
     */
    public List<FormerJournal> getFormerJournal() {
        if (formerJournal == null) {
            formerJournal = new ArrayList<FormerJournal>();
        }
        return this.formerJournal;
    }

    /**
     * Gets the value of the historyTitle property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryTitle }
     *     
     */
    public HistoryTitle getHistoryTitle() {
        return historyTitle;
    }

    /**
     * Sets the value of the historyTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryTitle }
     *     
     */
    public void setHistoryTitle(HistoryTitle value) {
        this.historyTitle = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczI18NText }
     * 
     * 
     */
    public List<DmlczI18NText> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<DmlczI18NText>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the pubHouse property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczI18NText }
     *     
     */
    public DmlczI18NText getPubHouse() {
        return pubHouse;
    }

    /**
     * Sets the value of the pubHouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczI18NText }
     *     
     */
    public void setPubHouse(DmlczI18NText value) {
        this.pubHouse = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczI18NText }
     *     
     */
    public DmlczI18NText getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczI18NText }
     *     
     */
    public void setPlace(DmlczI18NText value) {
        this.place = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguage() {
        if (language == null) {
            language = new ArrayList<String>();
        }
        return this.language;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStart(Integer value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEnd(Integer value) {
        this.end = value;
    }

    /**
     * Gets the value of the periodicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicity() {
        return periodicity;
    }

    /**
     * Sets the value of the periodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicity(String value) {
        this.periodicity = value;
    }

    /**
     * Gets the value of the editorEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditorEmail() {
        return editorEmail;
    }

    /**
     * Sets the value of the editorEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditorEmail(String value) {
        this.editorEmail = value;
    }

    /**
     * Gets the value of the watchEmail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the watchEmail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWatchEmail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWatchEmail() {
        if (watchEmail == null) {
            watchEmail = new ArrayList<String>();
        }
        return this.watchEmail;
    }

    /**
     * Gets the value of the movingWall property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMovingWall() {
        return movingWall;
    }

    /**
     * Sets the value of the movingWall property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMovingWall(BigInteger value) {
        this.movingWall = value;
    }

    /**
     * Gets the value of the paperSize property.
     * 
     * @return
     *     possible object is
     *     {@link DmlczPaperSize }
     *     
     */
    public DmlczPaperSize getPaperSize() {
        return paperSize;
    }

    /**
     * Sets the value of the paperSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmlczPaperSize }
     *     
     */
    public void setPaperSize(DmlczPaperSize value) {
        this.paperSize = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DmlczNote }
     * 
     * 
     */
    public List<DmlczNote> getNote() {
        if (note == null) {
            note = new ArrayList<DmlczNote>();
        }
        return this.note;
    }

    /**
     * Gets the value of the userRight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userRight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserRight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserRight }
     * 
     * 
     */
    public List<UserRight> getUserRight() {
        if (userRight == null) {
            userRight = new ArrayList<UserRight>();
        }
        return this.userRight;
    }

    /**
     * Gets the value of the volume property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the volume property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVolume().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Volume }
     * 
     * 
     */
    public List<Volume> getVolume() {
        if (volume == null) {
            volume = new ArrayList<Volume>();
        }
        return this.volume;
    }

}
