//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 01:41:46 PM CET 
//


package cz.muni.ics.digilaw.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ffMonographCatetory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ffMonographCatetory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="singlebooks"/>
 *     &lt;enumeration value="bookseries"/>
 *     &lt;enumeration value="bookseriesspisyff"/>
 *     &lt;enumeration value="bookseriesnumbered"/>
 *     &lt;enumeration value="bookseriesunnumbered"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ffMonographCatetory")
@XmlEnum
public enum FfMonographCatetory {

    @XmlEnumValue("singlebooks")
    SINGLEBOOKS("singlebooks"),
    @XmlEnumValue("bookseries")
    BOOKSERIES("bookseries"),
    @XmlEnumValue("bookseriesspisyff")
    BOOKSERIESSPISYFF("bookseriesspisyff"),
    @XmlEnumValue("bookseriesnumbered")
    BOOKSERIESNUMBERED("bookseriesnumbered"),
    @XmlEnumValue("bookseriesunnumbered")
    BOOKSERIESUNNUMBERED("bookseriesunnumbered");
    private final String value;

    FfMonographCatetory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FfMonographCatetory fromValue(String v) {
        for (FfMonographCatetory c: FfMonographCatetory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
