//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.09 at 03:34:01 PM CEST 
//


package cz.muni.ics.digilaw.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ffPartType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ffPartType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Review"/>
 *     &lt;enumeration value="News"/>
 *     &lt;enumeration value="Chapter"/>
 *     &lt;enumeration value="Article-Part"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ffPartType")
@XmlEnum
public enum FfPartType {

    @XmlEnumValue("Review")
    REVIEW("Review"),
    @XmlEnumValue("News")
    NEWS("News"),
    @XmlEnumValue("Chapter")
    CHAPTER("Chapter"),
    @XmlEnumValue("Article-Part")
    ARTICLE_PART("Article-Part");
    private final String value;

    FfPartType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FfPartType fromValue(String v) {
        for (FfPartType c: FfPartType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
