//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.23 at 09:17:16 AM CET 
//


package cz.muni.ics.digilaw.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ffPDFOrigin.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ffPDFOrigin">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="scan"/>
 *     &lt;enumeration value="borndigital"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ffPDFOrigin")
@XmlEnum
public enum FfPDFOrigin {

    @XmlEnumValue("scan")
    SCAN("scan"),
    @XmlEnumValue("borndigital")
    BORNDIGITAL("borndigital");
    private final String value;

    FfPDFOrigin(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FfPDFOrigin fromValue(String v) {
        for (FfPDFOrigin c: FfPDFOrigin.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
