//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.20 at 03:29:38 PM CET 
//


package cz.muni.ics.digilaw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Title"/>
 *         &lt;element ref="{}TitleVariant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CreatorPersonalName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CreatorCorporateName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Contributor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Edition" minOccurs="0"/>
 *         &lt;element ref="{}PublPlace" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Publisher" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PublYear" minOccurs="0"/>
 *         &lt;element ref="{}FormatExtent" minOccurs="0"/>
 *         &lt;element ref="{}Series" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Event" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Note" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ISBN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Language" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SubjectPHNK" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SubjectKeyword" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}BiblioCitation" minOccurs="0"/>
 *         &lt;element ref="{}RightsHolder" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}RightsAccess" minOccurs="0"/>
 *         &lt;element ref="{}RightsLicense" minOccurs="0"/>
 *         &lt;element ref="{}RightsURI" minOccurs="0"/>
 *         &lt;element ref="{}OpenAccess" minOccurs="0"/>
 *         &lt;element ref="{}EmbargoEndDate" minOccurs="0"/>
 *         &lt;element ref="{}Project" minOccurs="0"/>
 *         &lt;element ref="{}ProjectNumber" minOccurs="0"/>
 *         &lt;element ref="{}LinkToRelatedDocument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ExternalContent" minOccurs="0"/>
 *         &lt;element ref="{}LinkToReal" minOccurs="0"/>
 *         &lt;element ref="{}LinkToRealDesc" minOccurs="0"/>
 *         &lt;element ref="{}LinkToVirtual" minOccurs="0"/>
 *         &lt;element ref="{}LinkToVirtualDesc" minOccurs="0"/>
 *         &lt;element ref="{}LinkToVirtualDescNum" minOccurs="0"/>
 *         &lt;element ref="{}AlephSysno" minOccurs="0"/>
 *         &lt;element ref="{}Department" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PDFOrigin" minOccurs="0"/>
 *         &lt;element ref="{}LinkInMUCatalog" minOccurs="0"/>
 *         &lt;element ref="{}PageSize" minOccurs="0"/>
 *         &lt;element ref="{}Warning" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "titleVariant",
    "creatorPersonalName",
    "creatorCorporateName",
    "contributor",
    "edition",
    "publPlace",
    "publisher",
    "publYear",
    "formatExtent",
    "series",
    "event",
    "note",
    "isbn",
    "language",
    "description",
    "subjectPHNK",
    "subjectKeyword",
    "biblioCitation",
    "rightsHolder",
    "rightsAccess",
    "rightsLicense",
    "rightsURI",
    "openAccess",
    "embargoEndDate",
    "project",
    "projectNumber",
    "linkToRelatedDocument",
    "externalContent",
    "linkToReal",
    "linkToRealDesc",
    "linkToVirtual",
    "linkToVirtualDesc",
    "linkToVirtualDescNum",
    "alephSysno",
    "department",
    "pdfOrigin",
    "linkInMUCatalog",
    "pageSize",
    "warning"
})
@XmlRootElement(name = "Monography")
public class Monography {

    @XmlElement(name = "Title", required = true)
    protected Title title;
    @XmlElement(name = "TitleVariant")
    protected List<TitleVariant> titleVariant;
    @XmlElement(name = "CreatorPersonalName")
    protected List<CreatorPersonalName> creatorPersonalName;
    @XmlElement(name = "CreatorCorporateName")
    protected List<CreatorCorporateName> creatorCorporateName;
    @XmlElement(name = "Contributor")
    protected List<Contributor> contributor;
    @XmlElement(name = "Edition")
    protected String edition;
    @XmlElement(name = "PublPlace")
    protected List<String> publPlace;
    @XmlElement(name = "Publisher")
    protected List<String> publisher;
    @XmlElement(name = "PublYear")
    protected String publYear;
    @XmlElement(name = "FormatExtent")
    protected String formatExtent;
    @XmlElement(name = "Series")
    protected List<Series> series;
    @XmlElement(name = "Event")
    protected List<String> event;
    @XmlElement(name = "Note")
    protected List<Note> note;
    @XmlElement(name = "ISBN")
    protected List<String> isbn;
    @XmlElement(name = "Language")
    protected List<String> language;
    @XmlElement(name = "Description")
    protected List<Description> description;
    @XmlElement(name = "SubjectPHNK")
    protected List<String> subjectPHNK;
    @XmlElement(name = "SubjectKeyword")
    protected List<SubjectKeyword> subjectKeyword;
    @XmlElement(name = "BiblioCitation")
    protected String biblioCitation;
    @XmlElement(name = "RightsHolder")
    protected List<String> rightsHolder;
    @XmlElement(name = "RightsAccess")
    protected FfRightsAccess rightsAccess;
    @XmlElement(name = "RightsLicense")
    protected FfRightsLicense rightsLicense;
    @XmlElement(name = "RightsURI")
    protected String rightsURI;
    @XmlElement(name = "OpenAccess")
    protected FfOpenAccess openAccess;
    @XmlElement(name = "EmbargoEndDate")
    protected String embargoEndDate;
    @XmlElement(name = "Project")
    protected String project;
    @XmlElement(name = "ProjectNumber")
    protected String projectNumber;
    @XmlElement(name = "LinkToRelatedDocument")
    protected List<String> linkToRelatedDocument;
    @XmlElement(name = "ExternalContent")
    protected String externalContent;
    @XmlElement(name = "LinkToReal")
    protected String linkToReal;
    @XmlElement(name = "LinkToRealDesc")
    protected String linkToRealDesc;
    @XmlElement(name = "LinkToVirtual")
    protected String linkToVirtual;
    @XmlElement(name = "LinkToVirtualDesc")
    protected String linkToVirtualDesc;
    @XmlElement(name = "LinkToVirtualDescNum")
    protected String linkToVirtualDescNum;
    @XmlElement(name = "AlephSysno")
    protected String alephSysno;
    @XmlElement(name = "Department")
    protected List<FfDepartment> department;
    @XmlElement(name = "PDFOrigin")
    protected FfPDFOrigin pdfOrigin;
    @XmlElement(name = "LinkInMUCatalog")
    protected FfLinkInMUCatalog linkInMUCatalog;
    @XmlElement(name = "PageSize")
    protected PageSize pageSize;
    @XmlElement(name = "Warning")
    protected List<String> warning;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Title }
     *     
     */
    public Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Title }
     *     
     */
    public void setTitle(Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the titleVariant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleVariant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleVariant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleVariant }
     * 
     * 
     */
    public List<TitleVariant> getTitleVariant() {
        if (titleVariant == null) {
            titleVariant = new ArrayList<TitleVariant>();
        }
        return this.titleVariant;
    }

    /**
     * Gets the value of the creatorPersonalName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creatorPersonalName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreatorPersonalName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreatorPersonalName }
     * 
     * 
     */
    public List<CreatorPersonalName> getCreatorPersonalName() {
        if (creatorPersonalName == null) {
            creatorPersonalName = new ArrayList<CreatorPersonalName>();
        }
        return this.creatorPersonalName;
    }

    /**
     * Gets the value of the creatorCorporateName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creatorCorporateName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreatorCorporateName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreatorCorporateName }
     * 
     * 
     */
    public List<CreatorCorporateName> getCreatorCorporateName() {
        if (creatorCorporateName == null) {
            creatorCorporateName = new ArrayList<CreatorCorporateName>();
        }
        return this.creatorCorporateName;
    }

    /**
     * Gets the value of the contributor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contributor }
     * 
     * 
     */
    public List<Contributor> getContributor() {
        if (contributor == null) {
            contributor = new ArrayList<Contributor>();
        }
        return this.contributor;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdition(String value) {
        this.edition = value;
    }

    /**
     * Gets the value of the publPlace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publPlace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublPlace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPublPlace() {
        if (publPlace == null) {
            publPlace = new ArrayList<String>();
        }
        return this.publPlace;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<String>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the publYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublYear() {
        return publYear;
    }

    /**
     * Sets the value of the publYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublYear(String value) {
        this.publYear = value;
    }

    /**
     * Gets the value of the formatExtent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatExtent() {
        return formatExtent;
    }

    /**
     * Sets the value of the formatExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatExtent(String value) {
        this.formatExtent = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the series property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Series }
     * 
     * 
     */
    public List<Series> getSeries() {
        if (series == null) {
            series = new ArrayList<Series>();
        }
        return this.series;
    }

    /**
     * Gets the value of the event property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEvent() {
        if (event == null) {
            event = new ArrayList<String>();
        }
        return this.event;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Note }
     * 
     * 
     */
    public List<Note> getNote() {
        if (note == null) {
            note = new ArrayList<Note>();
        }
        return this.note;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isbn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getISBN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getISBN() {
        if (isbn == null) {
            isbn = new ArrayList<String>();
        }
        return this.isbn;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguage() {
        if (language == null) {
            language = new ArrayList<String>();
        }
        return this.language;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * 
     * 
     */
    public List<Description> getDescription() {
        if (description == null) {
            description = new ArrayList<Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the subjectPHNK property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subjectPHNK property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubjectPHNK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSubjectPHNK() {
        if (subjectPHNK == null) {
            subjectPHNK = new ArrayList<String>();
        }
        return this.subjectPHNK;
    }

    /**
     * Gets the value of the subjectKeyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subjectKeyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubjectKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubjectKeyword }
     * 
     * 
     */
    public List<SubjectKeyword> getSubjectKeyword() {
        if (subjectKeyword == null) {
            subjectKeyword = new ArrayList<SubjectKeyword>();
        }
        return this.subjectKeyword;
    }

    /**
     * Gets the value of the biblioCitation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiblioCitation() {
        return biblioCitation;
    }

    /**
     * Sets the value of the biblioCitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiblioCitation(String value) {
        this.biblioCitation = value;
    }

    /**
     * Gets the value of the rightsHolder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rightsHolder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRightsHolder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRightsHolder() {
        if (rightsHolder == null) {
            rightsHolder = new ArrayList<String>();
        }
        return this.rightsHolder;
    }

    /**
     * Gets the value of the rightsAccess property.
     * 
     * @return
     *     possible object is
     *     {@link FfRightsAccess }
     *     
     */
    public FfRightsAccess getRightsAccess() {
        return rightsAccess;
    }

    /**
     * Sets the value of the rightsAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link FfRightsAccess }
     *     
     */
    public void setRightsAccess(FfRightsAccess value) {
        this.rightsAccess = value;
    }

    /**
     * Gets the value of the rightsLicense property.
     * 
     * @return
     *     possible object is
     *     {@link FfRightsLicense }
     *     
     */
    public FfRightsLicense getRightsLicense() {
        return rightsLicense;
    }

    /**
     * Sets the value of the rightsLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link FfRightsLicense }
     *     
     */
    public void setRightsLicense(FfRightsLicense value) {
        this.rightsLicense = value;
    }

    /**
     * Gets the value of the rightsURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightsURI() {
        return rightsURI;
    }

    /**
     * Sets the value of the rightsURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightsURI(String value) {
        this.rightsURI = value;
    }

    /**
     * Gets the value of the openAccess property.
     * 
     * @return
     *     possible object is
     *     {@link FfOpenAccess }
     *     
     */
    public FfOpenAccess getOpenAccess() {
        return openAccess;
    }

    /**
     * Sets the value of the openAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link FfOpenAccess }
     *     
     */
    public void setOpenAccess(FfOpenAccess value) {
        this.openAccess = value;
    }

    /**
     * Gets the value of the embargoEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmbargoEndDate() {
        return embargoEndDate;
    }

    /**
     * Sets the value of the embargoEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmbargoEndDate(String value) {
        this.embargoEndDate = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProject(String value) {
        this.project = value;
    }

    /**
     * Gets the value of the projectNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectNumber() {
        return projectNumber;
    }

    /**
     * Sets the value of the projectNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectNumber(String value) {
        this.projectNumber = value;
    }

    /**
     * Gets the value of the linkToRelatedDocument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkToRelatedDocument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkToRelatedDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLinkToRelatedDocument() {
        if (linkToRelatedDocument == null) {
            linkToRelatedDocument = new ArrayList<String>();
        }
        return this.linkToRelatedDocument;
    }

    /**
     * Gets the value of the externalContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalContent() {
        return externalContent;
    }

    /**
     * Sets the value of the externalContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalContent(String value) {
        this.externalContent = value;
    }

    /**
     * Gets the value of the linkToReal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToReal() {
        return linkToReal;
    }

    /**
     * Sets the value of the linkToReal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToReal(String value) {
        this.linkToReal = value;
    }

    /**
     * Gets the value of the linkToRealDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToRealDesc() {
        return linkToRealDesc;
    }

    /**
     * Sets the value of the linkToRealDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToRealDesc(String value) {
        this.linkToRealDesc = value;
    }

    /**
     * Gets the value of the linkToVirtual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToVirtual() {
        return linkToVirtual;
    }

    /**
     * Sets the value of the linkToVirtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToVirtual(String value) {
        this.linkToVirtual = value;
    }

    /**
     * Gets the value of the linkToVirtualDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToVirtualDesc() {
        return linkToVirtualDesc;
    }

    /**
     * Sets the value of the linkToVirtualDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToVirtualDesc(String value) {
        this.linkToVirtualDesc = value;
    }

    /**
     * Gets the value of the linkToVirtualDescNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToVirtualDescNum() {
        return linkToVirtualDescNum;
    }

    /**
     * Sets the value of the linkToVirtualDescNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToVirtualDescNum(String value) {
        this.linkToVirtualDescNum = value;
    }

    /**
     * Gets the value of the alephSysno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlephSysno() {
        return alephSysno;
    }

    /**
     * Sets the value of the alephSysno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlephSysno(String value) {
        this.alephSysno = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the department property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepartment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FfDepartment }
     * 
     * 
     */
    public List<FfDepartment> getDepartment() {
        if (department == null) {
            department = new ArrayList<FfDepartment>();
        }
        return this.department;
    }

    /**
     * Gets the value of the pdfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link FfPDFOrigin }
     *     
     */
    public FfPDFOrigin getPDFOrigin() {
        return pdfOrigin;
    }

    /**
     * Sets the value of the pdfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link FfPDFOrigin }
     *     
     */
    public void setPDFOrigin(FfPDFOrigin value) {
        this.pdfOrigin = value;
    }

    /**
     * Gets the value of the linkInMUCatalog property.
     * 
     * @return
     *     possible object is
     *     {@link FfLinkInMUCatalog }
     *     
     */
    public FfLinkInMUCatalog getLinkInMUCatalog() {
        return linkInMUCatalog;
    }

    /**
     * Sets the value of the linkInMUCatalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link FfLinkInMUCatalog }
     *     
     */
    public void setLinkInMUCatalog(FfLinkInMUCatalog value) {
        this.linkInMUCatalog = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link PageSize }
     *     
     */
    public PageSize getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageSize }
     *     
     */
    public void setPageSize(PageSize value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warning property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarning().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWarning() {
        if (warning == null) {
            warning = new ArrayList<String>();
        }
        return this.warning;
    }

}
