//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.09 at 03:34:01 PM CEST 
//


package cz.muni.ics.digilaw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Title" maxOccurs="unbounded"/>
 *         &lt;element ref="{}TitleVariant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ISSN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Publisher" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PublicationStart" minOccurs="0"/>
 *         &lt;element ref="{}PublicationEnd" minOccurs="0"/>
 *         &lt;element ref="{}MovingWall" minOccurs="0"/>
 *         &lt;element ref="{}LinkToReal" minOccurs="0"/>
 *         &lt;element ref="{}LinkToRealDesc" minOccurs="0"/>
 *         &lt;element ref="{}LinkToVirtual" minOccurs="0"/>
 *         &lt;element ref="{}LinkToVirtualDesc" minOccurs="0"/>
 *         &lt;element ref="{}Note" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Warning" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Category" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "titleVariant",
    "description",
    "issn",
    "publisher",
    "publicationStart",
    "publicationEnd",
    "movingWall",
    "linkToReal",
    "linkToRealDesc",
    "linkToVirtual",
    "linkToVirtualDesc",
    "note",
    "warning",
    "category"
})
@XmlRootElement(name = "MonographicSeries")
public class MonographicSeries {

    @XmlElement(name = "Title", required = true)
    protected List<Title> title;
    @XmlElement(name = "TitleVariant")
    protected List<TitleVariant> titleVariant;
    @XmlElement(name = "Description")
    protected List<Description> description;
    @XmlElement(name = "ISSN")
    protected List<String> issn;
    @XmlElement(name = "Publisher")
    protected List<String> publisher;
    @XmlElement(name = "PublicationStart")
    protected String publicationStart;
    @XmlElement(name = "PublicationEnd")
    protected String publicationEnd;
    @XmlElement(name = "MovingWall")
    protected String movingWall;
    @XmlElement(name = "LinkToReal")
    protected String linkToReal;
    @XmlElement(name = "LinkToRealDesc")
    protected String linkToRealDesc;
    @XmlElement(name = "LinkToVirtual")
    protected String linkToVirtual;
    @XmlElement(name = "LinkToVirtualDesc")
    protected String linkToVirtualDesc;
    @XmlElement(name = "Note")
    protected List<Note> note;
    @XmlElement(name = "Warning")
    protected List<String> warning;
    @XmlElement(name = "Category")
    protected FfMonographCatetory category;

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Title }
     * 
     * 
     */
    public List<Title> getTitle() {
        if (title == null) {
            title = new ArrayList<Title>();
        }
        return this.title;
    }

    /**
     * Gets the value of the titleVariant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleVariant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleVariant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleVariant }
     * 
     * 
     */
    public List<TitleVariant> getTitleVariant() {
        if (titleVariant == null) {
            titleVariant = new ArrayList<TitleVariant>();
        }
        return this.titleVariant;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * 
     * 
     */
    public List<Description> getDescription() {
        if (description == null) {
            description = new ArrayList<Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the issn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getISSN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getISSN() {
        if (issn == null) {
            issn = new ArrayList<String>();
        }
        return this.issn;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<String>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the publicationStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationStart() {
        return publicationStart;
    }

    /**
     * Sets the value of the publicationStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationStart(String value) {
        this.publicationStart = value;
    }

    /**
     * Gets the value of the publicationEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationEnd() {
        return publicationEnd;
    }

    /**
     * Sets the value of the publicationEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationEnd(String value) {
        this.publicationEnd = value;
    }

    /**
     * Gets the value of the movingWall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovingWall() {
        return movingWall;
    }

    /**
     * Sets the value of the movingWall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovingWall(String value) {
        this.movingWall = value;
    }

    /**
     * Gets the value of the linkToReal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToReal() {
        return linkToReal;
    }

    /**
     * Sets the value of the linkToReal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToReal(String value) {
        this.linkToReal = value;
    }

    /**
     * Gets the value of the linkToRealDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToRealDesc() {
        return linkToRealDesc;
    }

    /**
     * Sets the value of the linkToRealDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToRealDesc(String value) {
        this.linkToRealDesc = value;
    }

    /**
     * Gets the value of the linkToVirtual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToVirtual() {
        return linkToVirtual;
    }

    /**
     * Sets the value of the linkToVirtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToVirtual(String value) {
        this.linkToVirtual = value;
    }

    /**
     * Gets the value of the linkToVirtualDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToVirtualDesc() {
        return linkToVirtualDesc;
    }

    /**
     * Sets the value of the linkToVirtualDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToVirtualDesc(String value) {
        this.linkToVirtualDesc = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Note }
     * 
     * 
     */
    public List<Note> getNote() {
        if (note == null) {
            note = new ArrayList<Note>();
        }
        return this.note;
    }

    /**
     * Gets the value of the warning property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warning property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarning().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWarning() {
        if (warning == null) {
            warning = new ArrayList<String>();
        }
        return this.warning;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link FfMonographCatetory }
     *     
     */
    public FfMonographCatetory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link FfMonographCatetory }
     *     
     */
    public void setCategory(FfMonographCatetory value) {
        this.category = value;
    }

}
