//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 01:41:46 PM CET 
//


package cz.muni.ics.digilaw.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.muni.ics.digilaw.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LinkToReal_QNAME = new QName("", "LinkToReal");
    private final static QName _ReviewedWork_QNAME = new QName("", "ReviewedWork");
    private final static QName _LinkInMUCatalog_QNAME = new QName("", "LinkInMUCatalog");
    private final static QName _RightsAccess_QNAME = new QName("", "RightsAccess");
    private final static QName _ISBN_QNAME = new QName("", "ISBN");
    private final static QName _SubjectPHNK_QNAME = new QName("", "SubjectPHNK");
    private final static QName _ChapterNumber_QNAME = new QName("", "ChapterNumber");
    private final static QName _Warning_QNAME = new QName("", "Warning");
    private final static QName _PublYear_QNAME = new QName("", "PublYear");
    private final static QName _RightsLicense_QNAME = new QName("", "RightsLicense");
    private final static QName _PDFOrigin_QNAME = new QName("", "PDFOrigin");
    private final static QName _LinkToRelatedDocument_QNAME = new QName("", "LinkToRelatedDocument");
    private final static QName _PartAuthor_QNAME = new QName("", "PartAuthor");
    private final static QName _ExternalContent_QNAME = new QName("", "ExternalContent");
    private final static QName _LinkToRealDesc_QNAME = new QName("", "LinkToRealDesc");
    private final static QName _PageSizeWidth_QNAME = new QName("", "PageSizeWidth");
    private final static QName _PartTitle_QNAME = new QName("", "PartTitle");
    private final static QName _OpenAccess_QNAME = new QName("", "OpenAccess");
    private final static QName _Project_QNAME = new QName("", "Project");
    private final static QName _PublicationStart_QNAME = new QName("", "PublicationStart");
    private final static QName _Department_QNAME = new QName("", "Department");
    private final static QName _RightsURI_QNAME = new QName("", "RightsURI");
    private final static QName _PublPlace_QNAME = new QName("", "PublPlace");
    private final static QName _EmbargoEndDate_QNAME = new QName("", "EmbargoEndDate");
    private final static QName _PublicationEnd_QNAME = new QName("", "PublicationEnd");
    private final static QName _Subject_QNAME = new QName("", "Subject");
    private final static QName _BiblioCitation_QNAME = new QName("", "BiblioCitation");
    private final static QName _Event_QNAME = new QName("", "Event");
    private final static QName _MovingWall_QNAME = new QName("", "MovingWall");
    private final static QName _Pagination_QNAME = new QName("", "Pagination");
    private final static QName _LinkToVirtual_QNAME = new QName("", "LinkToVirtual");
    private final static QName _Summary_QNAME = new QName("", "Summary");
    private final static QName _FontType_QNAME = new QName("", "FontType");
    private final static QName _Publisher_QNAME = new QName("", "Publisher");
    private final static QName _Category_QNAME = new QName("", "Category");
    private final static QName _ProjectNumber_QNAME = new QName("", "ProjectNumber");
    private final static QName _Link_QNAME = new QName("", "Link");
    private final static QName _ISSN_QNAME = new QName("", "ISSN");
    private final static QName _Edition_QNAME = new QName("", "Edition");
    private final static QName _LinkToVirtualDesc_QNAME = new QName("", "LinkToVirtualDesc");
    private final static QName _PDFPageRange_QNAME = new QName("", "PDFPageRange");
    private final static QName _PageSizeHeight_QNAME = new QName("", "PageSizeHeight");
    private final static QName _VolumeName_QNAME = new QName("", "VolumeName");
    private final static QName _AlephSysno_QNAME = new QName("", "AlephSysno");
    private final static QName _Language_QNAME = new QName("", "Language");
    private final static QName _LinkToVirtualDescNum_QNAME = new QName("", "LinkToVirtualDescNum");
    private final static QName _FormatExtent_QNAME = new QName("", "FormatExtent");
    private final static QName _RightsHolder_QNAME = new QName("", "RightsHolder");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.muni.ics.digilaw.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Monography }
     * 
     */
    public Monography createMonography() {
        return new Monography();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link TitleVariant }
     * 
     */
    public TitleVariant createTitleVariant() {
        return new TitleVariant();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public Contributor createContributor() {
        return new Contributor();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link DescribedURL }
     * 
     */
    public DescribedURL createDescribedURL() {
        return new DescribedURL();
    }

    /**
     * Create an instance of {@link RelatedDocument }
     * 
     */
    public RelatedDocument createRelatedDocument() {
        return new RelatedDocument();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link PageSize }
     * 
     */
    public PageSize createPageSize() {
        return new PageSize();
    }

    /**
     * Create an instance of {@link SubjectKeyword }
     * 
     */
    public SubjectKeyword createSubjectKeyword() {
        return new SubjectKeyword();
    }

    /**
     * Create an instance of {@link CreatorPersonalName }
     * 
     */
    public CreatorPersonalName createCreatorPersonalName() {
        return new CreatorPersonalName();
    }

    /**
     * Create an instance of {@link MonographicSeries }
     * 
     */
    public MonographicSeries createMonographicSeries() {
        return new MonographicSeries();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link MonographyChapter }
     * 
     */
    public MonographyChapter createMonographyChapter() {
        return new MonographyChapter();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link Volume }
     * 
     */
    public Volume createVolume() {
        return new Volume();
    }

    /**
     * Create an instance of {@link CreatorCorporateName }
     * 
     */
    public CreatorCorporateName createCreatorCorporateName() {
        return new CreatorCorporateName();
    }

    /**
     * Create an instance of {@link I18NText }
     * 
     */
    public I18NText createI18NText() {
        return new I18NText();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToReal")
    public JAXBElement<String> createLinkToReal(String value) {
        return new JAXBElement<String>(_LinkToReal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReviewedWork")
    public JAXBElement<String> createReviewedWork(String value) {
        return new JAXBElement<String>(_ReviewedWork_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfLinkInMUCatalog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkInMUCatalog")
    public JAXBElement<FfLinkInMUCatalog> createLinkInMUCatalog(FfLinkInMUCatalog value) {
        return new JAXBElement<FfLinkInMUCatalog>(_LinkInMUCatalog_QNAME, FfLinkInMUCatalog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfRightsAccess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RightsAccess")
    public JAXBElement<FfRightsAccess> createRightsAccess(FfRightsAccess value) {
        return new JAXBElement<FfRightsAccess>(_RightsAccess_QNAME, FfRightsAccess.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ISBN")
    public JAXBElement<String> createISBN(String value) {
        return new JAXBElement<String>(_ISBN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubjectPHNK")
    public JAXBElement<String> createSubjectPHNK(String value) {
        return new JAXBElement<String>(_SubjectPHNK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChapterNumber")
    public JAXBElement<String> createChapterNumber(String value) {
        return new JAXBElement<String>(_ChapterNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Warning")
    public JAXBElement<String> createWarning(String value) {
        return new JAXBElement<String>(_Warning_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublYear")
    public JAXBElement<String> createPublYear(String value) {
        return new JAXBElement<String>(_PublYear_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfRightsLicense }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RightsLicense")
    public JAXBElement<FfRightsLicense> createRightsLicense(FfRightsLicense value) {
        return new JAXBElement<FfRightsLicense>(_RightsLicense_QNAME, FfRightsLicense.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfPDFOrigin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PDFOrigin")
    public JAXBElement<FfPDFOrigin> createPDFOrigin(FfPDFOrigin value) {
        return new JAXBElement<FfPDFOrigin>(_PDFOrigin_QNAME, FfPDFOrigin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToRelatedDocument")
    public JAXBElement<String> createLinkToRelatedDocument(String value) {
        return new JAXBElement<String>(_LinkToRelatedDocument_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartAuthor")
    public JAXBElement<String> createPartAuthor(String value) {
        return new JAXBElement<String>(_PartAuthor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExternalContent")
    public JAXBElement<String> createExternalContent(String value) {
        return new JAXBElement<String>(_ExternalContent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToRealDesc")
    public JAXBElement<String> createLinkToRealDesc(String value) {
        return new JAXBElement<String>(_LinkToRealDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PageSizeWidth")
    public JAXBElement<String> createPageSizeWidth(String value) {
        return new JAXBElement<String>(_PageSizeWidth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PartTitle")
    public JAXBElement<String> createPartTitle(String value) {
        return new JAXBElement<String>(_PartTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfOpenAccess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpenAccess")
    public JAXBElement<FfOpenAccess> createOpenAccess(FfOpenAccess value) {
        return new JAXBElement<FfOpenAccess>(_OpenAccess_QNAME, FfOpenAccess.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Project")
    public JAXBElement<String> createProject(String value) {
        return new JAXBElement<String>(_Project_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublicationStart")
    public JAXBElement<String> createPublicationStart(String value) {
        return new JAXBElement<String>(_PublicationStart_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfDepartment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Department")
    public JAXBElement<FfDepartment> createDepartment(FfDepartment value) {
        return new JAXBElement<FfDepartment>(_Department_QNAME, FfDepartment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RightsURI")
    public JAXBElement<String> createRightsURI(String value) {
        return new JAXBElement<String>(_RightsURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublPlace")
    public JAXBElement<String> createPublPlace(String value) {
        return new JAXBElement<String>(_PublPlace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmbargoEndDate")
    public JAXBElement<String> createEmbargoEndDate(String value) {
        return new JAXBElement<String>(_EmbargoEndDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublicationEnd")
    public JAXBElement<String> createPublicationEnd(String value) {
        return new JAXBElement<String>(_PublicationEnd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LawSubject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Subject")
    public JAXBElement<LawSubject> createSubject(LawSubject value) {
        return new JAXBElement<LawSubject>(_Subject_QNAME, LawSubject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BiblioCitation")
    public JAXBElement<String> createBiblioCitation(String value) {
        return new JAXBElement<String>(_BiblioCitation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Event")
    public JAXBElement<String> createEvent(String value) {
        return new JAXBElement<String>(_Event_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MovingWall")
    public JAXBElement<String> createMovingWall(String value) {
        return new JAXBElement<String>(_MovingWall_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pagination")
    public JAXBElement<String> createPagination(String value) {
        return new JAXBElement<String>(_Pagination_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToVirtual")
    public JAXBElement<String> createLinkToVirtual(String value) {
        return new JAXBElement<String>(_LinkToVirtual_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LawFontType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FontType")
    public JAXBElement<LawFontType> createFontType(LawFontType value) {
        return new JAXBElement<LawFontType>(_FontType_QNAME, LawFontType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Publisher")
    public JAXBElement<String> createPublisher(String value) {
        return new JAXBElement<String>(_Publisher_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfMonographCatetory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Category")
    public JAXBElement<FfMonographCatetory> createCategory(FfMonographCatetory value) {
        return new JAXBElement<FfMonographCatetory>(_Category_QNAME, FfMonographCatetory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProjectNumber")
    public JAXBElement<String> createProjectNumber(String value) {
        return new JAXBElement<String>(_ProjectNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Link")
    public JAXBElement<String> createLink(String value) {
        return new JAXBElement<String>(_Link_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ISSN")
    public JAXBElement<String> createISSN(String value) {
        return new JAXBElement<String>(_ISSN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Edition")
    public JAXBElement<String> createEdition(String value) {
        return new JAXBElement<String>(_Edition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToVirtualDesc")
    public JAXBElement<String> createLinkToVirtualDesc(String value) {
        return new JAXBElement<String>(_LinkToVirtualDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PDFPageRange")
    public JAXBElement<String> createPDFPageRange(String value) {
        return new JAXBElement<String>(_PDFPageRange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PageSizeHeight")
    public JAXBElement<String> createPageSizeHeight(String value) {
        return new JAXBElement<String>(_PageSizeHeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VolumeName")
    public JAXBElement<String> createVolumeName(String value) {
        return new JAXBElement<String>(_VolumeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AlephSysno")
    public JAXBElement<String> createAlephSysno(String value) {
        return new JAXBElement<String>(_AlephSysno_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LinkToVirtualDescNum")
    public JAXBElement<String> createLinkToVirtualDescNum(String value) {
        return new JAXBElement<String>(_LinkToVirtualDescNum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FormatExtent")
    public JAXBElement<String> createFormatExtent(String value) {
        return new JAXBElement<String>(_FormatExtent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RightsHolder")
    public JAXBElement<String> createRightsHolder(String value) {
        return new JAXBElement<String>(_RightsHolder_QNAME, String.class, null, value);
    }

}
