//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.09 at 03:34:01 PM CEST 
//


package cz.muni.ics.digilaw.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PageSizeWidth"/>
 *         &lt;element ref="{}PageSizeHeight"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pageSizeWidth",
    "pageSizeHeight"
})
@XmlRootElement(name = "PageSize")
public class PageSize {

    @XmlElement(name = "PageSizeWidth", required = true)
    protected String pageSizeWidth;
    @XmlElement(name = "PageSizeHeight", required = true)
    protected String pageSizeHeight;

    /**
     * Gets the value of the pageSizeWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageSizeWidth() {
        return pageSizeWidth;
    }

    /**
     * Sets the value of the pageSizeWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageSizeWidth(String value) {
        this.pageSizeWidth = value;
    }

    /**
     * Gets the value of the pageSizeHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageSizeHeight() {
        return pageSizeHeight;
    }

    /**
     * Sets the value of the pageSizeHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageSizeHeight(String value) {
        this.pageSizeHeight = value;
    }

}
