//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 01:41:29 PM CET 
//


package cz.muni.ics.digilaw.domain;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SerialTitle"/>
 *         &lt;element ref="{}TitleMain" minOccurs="0"/>
 *         &lt;element ref="{}TitleVariant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}TitleVariantMain" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Series" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ISBN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ISSN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Copyright" minOccurs="0"/>
 *         &lt;element ref="{}Note" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Language" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Publisher" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Periodicity" minOccurs="0"/>
 *         &lt;element ref="{}PublicationStart" minOccurs="0"/>
 *         &lt;element ref="{}PublicationEnd" minOccurs="0"/>
 *         &lt;element ref="{}MovingWall" minOccurs="0"/>
 *         &lt;element ref="{}HomeURL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PreviousSeries" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}NextSeries" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}LinkToReal" minOccurs="0"/>
 *         &lt;element ref="{}LinkToRealDesc" minOccurs="0"/>
 *         &lt;element ref="{}LinkToVirtual" minOccurs="0"/>
 *         &lt;element ref="{}LinkToVirtualDesc" minOccurs="0"/>
 *         &lt;element ref="{}Category" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serialTitle",
    "titleMain",
    "titleVariant",
    "titleVariantMain",
    "series",
    "isbn",
    "issn",
    "description",
    "copyright",
    "note",
    "language",
    "publisher",
    "periodicity",
    "publicationStart",
    "publicationEnd",
    "movingWall",
    "homeURL",
    "previousSeries",
    "nextSeries",
    "linkToReal",
    "linkToRealDesc",
    "linkToVirtual",
    "linkToVirtualDesc",
    "category"
})
@XmlRootElement(name = "Periodical")
public class Periodical {

    @XmlElement(name = "SerialTitle", required = true)
    protected String serialTitle;
    @XmlElement(name = "TitleMain")
    protected String titleMain;
    @XmlElement(name = "TitleVariant")
    protected List<String> titleVariant;
    @XmlElement(name = "TitleVariantMain")
    protected List<TitleVariantMain> titleVariantMain;
    @XmlElement(name = "Series")
    protected List<Series> series;
    @XmlElement(name = "ISBN")
    protected List<String> isbn;
    @XmlElement(name = "ISSN")
    protected List<String> issn;
    @XmlElement(name = "Description")
    protected List<Description> description;
    @XmlElement(name = "Copyright")
    protected String copyright;
    @XmlElement(name = "Note")
    protected List<Note> note;
    @XmlElement(name = "Language")
    protected List<String> language;
    @XmlElement(name = "Publisher")
    protected List<String> publisher;
    @XmlElement(name = "Periodicity")
    protected String periodicity;
    @XmlElement(name = "PublicationStart")
    protected BigInteger publicationStart;
    @XmlElement(name = "PublicationEnd")
    protected BigInteger publicationEnd;
    @XmlElement(name = "MovingWall")
    protected String movingWall;
    @XmlElement(name = "HomeURL")
    protected List<String> homeURL;
    @XmlElement(name = "PreviousSeries")
    protected List<String> previousSeries;
    @XmlElement(name = "NextSeries")
    protected List<String> nextSeries;
    @XmlElement(name = "LinkToReal")
    protected String linkToReal;
    @XmlElement(name = "LinkToRealDesc")
    protected String linkToRealDesc;
    @XmlElement(name = "LinkToVirtual")
    protected String linkToVirtual;
    @XmlElement(name = "LinkToVirtualDesc")
    protected String linkToVirtualDesc;
    @XmlElement(name = "Category")
    protected FfSerialCatetory category;

    /**
     * Gets the value of the serialTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialTitle() {
        return serialTitle;
    }

    /**
     * Sets the value of the serialTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialTitle(String value) {
        this.serialTitle = value;
    }

    /**
     * Gets the value of the titleMain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleMain() {
        return titleMain;
    }

    /**
     * Sets the value of the titleMain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleMain(String value) {
        this.titleMain = value;
    }

    /**
     * Gets the value of the titleVariant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleVariant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleVariant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTitleVariant() {
        if (titleVariant == null) {
            titleVariant = new ArrayList<String>();
        }
        return this.titleVariant;
    }

    /**
     * Gets the value of the titleVariantMain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleVariantMain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleVariantMain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleVariantMain }
     * 
     * 
     */
    public List<TitleVariantMain> getTitleVariantMain() {
        if (titleVariantMain == null) {
            titleVariantMain = new ArrayList<TitleVariantMain>();
        }
        return this.titleVariantMain;
    }

    /**
     * Gets the value of the series property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the series property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Series }
     * 
     * 
     */
    public List<Series> getSeries() {
        if (series == null) {
            series = new ArrayList<Series>();
        }
        return this.series;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isbn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getISBN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getISBN() {
        if (isbn == null) {
            isbn = new ArrayList<String>();
        }
        return this.isbn;
    }

    /**
     * Gets the value of the issn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getISSN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getISSN() {
        if (issn == null) {
            issn = new ArrayList<String>();
        }
        return this.issn;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * 
     * 
     */
    public List<Description> getDescription() {
        if (description == null) {
            description = new ArrayList<Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the note property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Note }
     * 
     * 
     */
    public List<Note> getNote() {
        if (note == null) {
            note = new ArrayList<Note>();
        }
        return this.note;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguage() {
        if (language == null) {
            language = new ArrayList<String>();
        }
        return this.language;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<String>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the periodicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicity() {
        return periodicity;
    }

    /**
     * Sets the value of the periodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicity(String value) {
        this.periodicity = value;
    }

    /**
     * Gets the value of the publicationStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPublicationStart() {
        return publicationStart;
    }

    /**
     * Sets the value of the publicationStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPublicationStart(BigInteger value) {
        this.publicationStart = value;
    }

    /**
     * Gets the value of the publicationEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPublicationEnd() {
        return publicationEnd;
    }

    /**
     * Sets the value of the publicationEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPublicationEnd(BigInteger value) {
        this.publicationEnd = value;
    }

    /**
     * Gets the value of the movingWall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovingWall() {
        return movingWall;
    }

    /**
     * Sets the value of the movingWall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovingWall(String value) {
        this.movingWall = value;
    }

    /**
     * Gets the value of the homeURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the homeURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHomeURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHomeURL() {
        if (homeURL == null) {
            homeURL = new ArrayList<String>();
        }
        return this.homeURL;
    }

    /**
     * Gets the value of the previousSeries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the previousSeries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreviousSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPreviousSeries() {
        if (previousSeries == null) {
            previousSeries = new ArrayList<String>();
        }
        return this.previousSeries;
    }

    /**
     * Gets the value of the nextSeries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nextSeries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNextSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNextSeries() {
        if (nextSeries == null) {
            nextSeries = new ArrayList<String>();
        }
        return this.nextSeries;
    }

    /**
     * Gets the value of the linkToReal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToReal() {
        return linkToReal;
    }

    /**
     * Sets the value of the linkToReal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToReal(String value) {
        this.linkToReal = value;
    }

    /**
     * Gets the value of the linkToRealDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToRealDesc() {
        return linkToRealDesc;
    }

    /**
     * Sets the value of the linkToRealDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToRealDesc(String value) {
        this.linkToRealDesc = value;
    }

    /**
     * Gets the value of the linkToVirtual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToVirtual() {
        return linkToVirtual;
    }

    /**
     * Sets the value of the linkToVirtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToVirtual(String value) {
        this.linkToVirtual = value;
    }

    /**
     * Gets the value of the linkToVirtualDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkToVirtualDesc() {
        return linkToVirtualDesc;
    }

    /**
     * Sets the value of the linkToVirtualDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkToVirtualDesc(String value) {
        this.linkToVirtualDesc = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link FfSerialCatetory }
     *     
     */
    public FfSerialCatetory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link FfSerialCatetory }
     *     
     */
    public void setCategory(FfSerialCatetory value) {
        this.category = value;
    }

}
